#scrape_configs:
#  - job_name: prometheus
#    scrape_interval: 5s
#    static_configs:
#    - targets:
#      - prometheus:9090
#      - node-exporter:9100
#      - cadvisor:8080

#  - job_name: docker
#    scrape_interval: 5s
#    static_configs:
#    - targets:
#      - docker:9323


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['prometheus:9090']  #add the private ip address

  - job_name: 'cadvisor'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']  #add the private ip address



#scrape_configs:
#  - job_name: 'cadvisor'
#    static_configs:
#      - targets: ['prometheus:9090, cadvisor:8080']
#    relabel_configs:
#      - source_labels: [container_name]
#        regex: 'apache'
#        action: keep
