#scrape_configs:
#  - job_name: prometheus
#    scrape_interval: 5s
#    static_configs:
#    - targets:
#      - prometheus:9090
#      - node-exporter:9100
#      - cadvisor:8080

#  - job_name: docker
#    scrape_interval: 5s
#    static_configs:
#    - targets:
#      - 172.20.0.1:9323


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['172.20.0.3:9090']

  - job_name: 'cadvisor'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['172.20.0.2:8080']



#scrape_configs:
#  - job_name: 'cadvisor'
#    static_configs:
#      - targets: ['172.20.0.3:9090, 172.20.0.2:8080']
#    relabel_configs:
#      - source_labels: [container_name]
#        regex: 'apache'
#        action: keep
